[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  OneWire
  DallasTemperature
  knolleary/PubSubClient

[env:esp32dev-real]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -D EDGE_BUILD_SIMULATOR=0

lib_deps =
  OneWire
  DallasTemperature
  knolleary/PubSubClient
