# Copy this file to:
# data-hub/config/application.properties
# and fill in your local credentials.

datahub.mqtt.uri=tcp://127.0.0.1:1883
datahub.mqtt.client-id=java-data-hub-v1
datahub.mqtt.username=
datahub.mqtt.password=
datahub.buffer-size=2048
datahub.processing-concurrency=8
