package com.edgehub.datahub.model;

public record TelemetryPayload(
    String device_id,
    long uptime_ms,
    double target_temp_c,
    double sim_temp_c,
    Double sensor_temp_c,
    double error_c,
    double integral_error,
    double control_output,
    int pwm_duty,
    double pwm_norm,
    Long control_period_ms,
    String saturation_state,
    Boolean sensor_valid,
    String run_id,
    String control_mode,
    String controller_version,
    double kp,
    double ki,
    double kd,
    String system_state,
    String sensor_status,
    Long actual_dt_ms,
    Long dt_error_ms,
    Boolean wifi_connected,
    Boolean mqtt_connected,
    Long mqtt_reconnect_count,
    Long mqtt_publish_fail_count,
    Boolean safety_output_forced_off,
    Boolean fault_latched,
    String fault_reason,
    Double software_max_safe_temp_c,
    boolean has_pending_params,
    long pending_params_age_ms) {}
